name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Grade use-secrets activity
        id: check-secrets
        run: |
          npm install
          node ./.github/actions/check-secrets-action
        env:
          secrets-context: ${{ secrets.adel2 }}
